package com.example.vipul.prac10;

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

    }


    public void msgVipul(View view) {
        Toast.makeText(getApplicationContext(), "This toast is generated by Sonu Kumar", Toast.LENGTH_LONG).show();

    }
}